### ISSUE TITLE
Migrate Arc's UD model layer into LocoKit

### ISSUE THREAD

**Issue by sobri909** [sobri909/ArcKit#44]
Arc keeps an extra layer of activity type ML models than LocoKit. The extra layer being the user's own personal models, based on their own type confirmations / corrections. 

- In LocoKit the tree is `GD2 -> GD1 -> GD0` (neighbourhood -> city -> world).
- In Arc the tree is `UD2 -> GD2 -> GD1 -> GD0` (personal neighbourhood -> shared neighbourhood -> city -> world).

So that UD2 layer needs to be migrated into LocoKit. 

This will also open the door for doing custom activity types directly in LocoKit (and also in Arc).

## Todos

- [ ] Migrate `UserActivityType` upstream
- [ ] Migrate `UserActivityTypeClassifier` upstream
- [ ] Migrate `UserTimelineClassifier` upstream
